#!/bin/bash

# Prepare Custom Bulk/Quick Edit for release
#
# @author Michael Cannon <mc@aihr.us>

KEY="cbqe"
DIR_UPLOAD="2013/06"
ID_POST=17428
ID_PRODUCT=17555

source ~/.skel/bin/custom/wpinit ${KEY}
echo

if [[ -z ${1} ]]
then
	echo "What's the version number?"
	echo
	exit 1
else
	VERSION=${1}
fi

wprelease ${KEY} ${VERSION} || exit 1;
wpsvn ${KEY} ${VERSION} || exit 1;
wpdocument ${KEY} ${DIR_UPLOAD} ${ID_POST} ${ID_PRODUCT}