#!/bin/bash

# Prepare Testimonials Widget for release
#
# @author Michael Cannon <mc@aihr.us>

KEY="tw"

source ~/.skel/bin/custom/wpinit ${KEY}
echo

if [[ -z ${1} ]]
then
	echo "What's the version number?"
	echo
	exit 1
fi

VERSION=${1}
wprelease ${KEY} ${VERSION} || exit 1;

# push svn and do WordPress release
cd ~/code/svn.wordpress
cd testimonials-widget
svn cleanup . || { echo "Unable to 'svn cleanup'"; exit 1; }
svn up --force || { echo "Unable to 'svn up --force'"; exit 1; }
git clone git@github.com:michael-cannon/testimonials-widget.git || exit 1;
cd testimonials-widget
rm -rf .git
cp -r * ../trunk/.
cd ../trunk
svn add *
cd ..
rm -rf testimonials-widget

if [[ ! -d "tags/${VERSION}" ]]
then
	svn cp trunk tags/${VERSION}
	svn ci -m "Release version ${VERSION}" || { echo "Unable to 'svn ci'"; exit 1; }
	svn status
else
	echo
	echo Manually merge SVN files
	echo "svn cp trunk tags/${VERSION}"
	echo "svn ci -m \"Release version ${VERSION}\""
	echo
fi

open http://wordpress.org/extend/plugins/about/validator/

mvim ${SITE_WP_PLUGINS}/testimonials-widget/changelog.txt
open http://aihr.us/wp-admin/post.php?post=16105\&action=edit

open http://testwp.localhost/wp-admin/update-core.php
open http://aihr.us/wp-admin/update-core.php
open http://wordpress.org/extend/plugins/testimonials-widget/