#!/bin/bash

# Prepare Custom Bulk/Quick Edit Premium for release
#
# @author Michael Cannon <mc@aihr.us>

KEY="cbqep"
DIR_UPLOAD="2012/06"
ID_POST=17433
ID_PRODUCT=17383
ID_CHANGELOG=17453
ID_API=17476

source ~/.skel/bin/custom/wpinit ${KEY}
echo

if [[ -z ${1} ]]
then
	echo "What's the version number?"
	echo
	exit 1
fi

VERSION=${1}
wprelease ${KEY} ${VERSION} || exit 1;
wpdocument ${KEY} ${DIR_UPLOAD} ${ID_POST} ${ID_PRODUCT} ${ID_CHANGELOG} ${ID_API}