#!/bin/bash

# Prepare Custom Bulk/Quick Edit Premium for release
#
# @author Michael Cannon <mc@aihr.us>

KEY="cbqep"

source ~/.skel/bin/custom/wpinit ${KEY}
echo

if [[ -z ${1} ]]
then
	echo "What's the version number?"
	echo
	exit 1
fi

VERSION=${1}
wprelease ${KEY} ${VERSION} || exit 1;

${CMD_SCP} ~/Downloads/zzz-wp/${PLUGIN}.zip aihrus@aihr.us:~/subdomains/updates/update/. || exit 1;
${CMD_SCP} ~/Downloads/zzz-wp/${PLUGIN}.zip aihrus@aihr.us:~/public_html/wp-content/uploads/edd/2012/06/. || exit 1;

open http://wordpress.org/extend/plugins/about/validator/

# changelog
open http://aihr.us/wp-admin/post.php?post=17453\&action=edit

mvim ${SITE_WP_PLUGINS}/${PLUGIN}/readme.txt
# details
open http://aihr.us/wp-admin/post.php?post=17433\&action=edit
# product
open http://aihr.us/wp-admin/post.php?post=17383\&action=edit

mvim ~/Sites/zzz/testimonials-widget-premium/packages.php
echo ${CMD_SCP} ~/Sites/zzz/testimonials-widget-premium/packages.php aihrus@aihr.us:~/subdomains/updates/packages.php
echo