#!/bin/bash

GREP="/usr/local/bin/grep -nrsI --exclude-dir=languages --exclude-dir=libraries"

clear
clear

echo
echo "Peimic"
${GREP} -e "Peimic\|peimic" *
echo
echo "Aihrus"
${GREP} -e "aihr.us\|Aihrus\|aihrus" *
echo
echo "Michael"
${GREP} -e "mc@\|Michael\|Michael Cannon\|michael@" *
echo
echo "2014"
${GREP} "2014" *
echo
echo "tests WordPress-Core"
${GREP} "WordPress-Core" ci
${GREP} "WordPress-Core" tests
echo
echo "saurabhd as contributor"
${GREP} "Contributors" *