#!/bin/bash

clear
clear

echo
echo "Peimic"
grep -nrsI -e "Peimic\|peimic" *
echo
echo "Aihrus"
grep -nrsI -e "aihr.us\|Aihrus\|aihrus" *
echo
echo "Michael"
grep -nrsI -e "mc@\|Michael\|Michael Cannon\|michael@" *
echo
echo "2014"
grep -nrsI "2014" *
echo
echo "saurabhd as contributor"
grep -nrsI "Contributors" *