#!/bin/bash

clear
clear

echo
echo "Peimic"
grep -nrsI --exclude-dir=languages -e "Peimic\|peimic" *
echo
echo "Aihrus"
grep -nrsI --exclude-dir=languages -e "aihr.us\|Aihrus\|aihrus" *
echo
echo "Michael"
grep -nrsI --exclude-dir=languages -e "mc@\|Michael\|Michael Cannon\|michael@" *
echo
echo "2014"
grep -nrsI --exclude-dir=languages "2014" *
echo
echo "saurabhd as contributor"
grep -nrsI --exclude-dir=languages "Contributors" *