#!/bin/bash

GREP="/usr/local/bin/grep -nrsI --exclude-dir=languages --exclude-dir=libraries"

clear
clear

# Update URLs
perl -pi -e "s#axelerant.cmo#axelerant.com#g" *.php *.md *.txt includes/*.php

perl -pi -e "s#\s+\(email:\s*info\@axelerant.com\)##g" *.php *.md *.txt includes/*.php
perl -pi -e "s#//axelerant.com/store/#//store.axelerant.com/#g" *.php *.md *.txt includes/*.php
perl -pi -e "s#/axelerant.com/become-beta-tester/#/store.axelerant.com/become-beta-tester/#g" *.php *.md *.txt includes/*.php
perl -pi -e "s#/axelerant.com/best-wordpress#/store.axelerant.com/best-wordpress#g" *.php *.md *.txt includes/*.php
perl -pi -e "s#/axelerant.com/custom-bulkquick#/store.axelerant.com/custom-bulkquick#g" *.php *.md *.txt includes/*.php
perl -pi -e "s#/axelerant.com/downloads#/store.axelerant.com/downloads#g" *.php *.md *.txt includes/*.php
perl -pi -e "s#/axelerant.com/testimonials-examples/#/store.axelerant.com/testimonials-examples/#g" *.php *.md *.txt includes/*.php
perl -pi -e "s#/axelerant.com/wordpress-bulk#/store.axelerant.com/wordpress-bulk#g" *.php *.md *.txt includes/*.php
perl -pi -e "s#http://axelerant#https://axelerant#g" *.php *.md *.txt includes/*.php
perl -pi -e "s#support\@axelerant.com#support\@nodedesk.com#g" *.php *.md *.txt includes/*.php

echo
echo "BRAND - Aihrus"
${GREP} -e "Aihrus\>\|aihrus\.{0}" *
echo
echo "BRAND - Michael"
${GREP} -e "mc@\|Michael\>\|Michael Cannon\|michael@" *
echo
echo "BRAND - Peimic"
${GREP} -e "Peimic\|peimic" *
echo
echo "DATE - 2014"
${GREP} "2014" *
echo
echo "EMAIL - @axelerant.com > @nodedesk.com"
${GREP} "@axelerant.com" *
echo
echo "SPELLING - axelerant.cmo"
${GREP} "axelerant.cmo" *
echo
echo "CONTRIBUTORS - ,saurabhd,subharanjan"
${GREP} "Contributors" *
echo
echo "REQS - Aihrus Framework 1.2.2"
${GREP} -e "AIHR_VERSION.*'1.2.2" *
echo
echo "TESTS - WordPress-Core"
${GREP} "WordPress-Core" ci tests
echo
echo "URL - aihr.us"
${GREP} -e "aihr.us\|aihrus\." *
echo
echo "URL - axelerant.com"
${GREP} -e "axelerant.com\|axelerant\." *
echo
echo "URL - https://nodedesk.zendesk.com/hc/en-us/articles/202381391"
${GREP} "https://aihrus.zendesk.com/entries/35689458" *