#!/bin/bash

# Prepare EDD Sales Recovery for release
#
# @author Michael Cannon <mc@aihr.us>

KEY="eddsr"
DIR_UPLOAD="2013/07"
ID_PRODUCT=0
ID_POST=17717
ID_CHANGELOG=17720
ID_API=17725
ID_TODO=17723

source ~/.skel/bin/wpinit ${KEY}
echo

if [[ -z ${1} ]]
then
	echo "What's the version number?"
	echo
	exit 1
fi

VERSION=${1}
wprelease ${KEY} ${VERSION} || exit 1;
wpdocument ${KEY} ${DIR_UPLOAD} ${ID_PRODUCT} ${ID_POST} ${ID_CHANGELOG} ${ID_API} ${ID_TODO}