#!/bin/bash

# Prepare EDD Retroactive Licensing for release
#
# @author Michael Cannon <mc@aihr.us>

KEY="erl"
DIR_UPLOAD="2013/11"
ID_PRODUCT=0
ID_POST=19212
ID_CHANGELOG=19214
ID_API=19216
ID_TODO=19218

source ~/.skel/bin/wpinit ${KEY}
echo

if [[ -z ${1} ]]
then
	echo "What's the version number?"
	echo
	exit 1
fi

VERSION=${1}
wprelease ${KEY} ${VERSION} || exit 1;
wpdocument ${KEY} ${DIR_UPLOAD} ${ID_PRODUCT} ${ID_POST} ${ID_CHANGELOG} ${ID_API} ${ID_TODO}