#!/bin/bash

# Prepare Flickr Shortcode Importer for release
#
# @author Michael Cannon <mc@aihr.us>

KEY="fsi"
DIR_UPLOAD="2013/05"
ID_PRODUCT=16732
ID_POST=0
ID_CHANGELOG=0
ID_API=0
ID_TODO=0

source ~/.skel/bin/wpinit ${KEY}
echo

if [[ -z ${1} ]]
then
	echo "What's the version number?"
	echo
	exit 1
else
	VERSION=${1}
fi

wprelease ${KEY} ${VERSION} || exit 1;

if [[ -n ${2} ]]
then
	wpsvn ${KEY} ${VERSION} || exit 1;
fi

wpdocument ${KEY} ${DIR_UPLOAD} ${ID_PRODUCT} ${ID_POST} ${ID_CHANGELOG} ${ID_API} ${ID_TODO}