#!/bin/bash

source ~/.skel/bin/wpinit ${@}
echo

LIB_DIR="includes/libraries"
LIB_AIHRUS="${LIB_DIR}/aihrus-framework"
if [[ ! -e ${LIB_DIR} ]]
then
	mkdir -p ${LIB_DIR}
fi

REMOTE_NAME="aihrus"

AIHRUS_VERSION=${AIHR_VERSION}
if [[ -n ${1} ]]
then
	AIHRUS_VERSION=${1}
else
	AIHRUS_VERSION="master"
fi

git remote add ${REMOTE_NAME} git@github.com:michael-cannon/aihrus-framework.git
git fetch ${REMOTE_NAME}
git subtree add -P ${LIB_AIHRUS} --squash ${REMOTE_NAME} ${AIHRUS_VERSION}
git commit -a -m "Add aihrus framework"
git push origin master
