#!/bin/bash

LIB_AIHRUS="includes/libraries/aihrus-framework"

if [[ -z ${1} ]]
then
	git subtree pull -P ${LIB_AIHRUS} -m 'Update aihrus framework' --squash aihrus master
	cp -r ~/Sites/wp/wp-content/plugins/aihrus-framework/* ${LIB_AIHRUS}/
	rm -rf ${LIB_AIHRUS}/.git
	git diff
	git status -sb
else
	git commit -a -m 'Update aihrus framework'
	git push origin master
fi
