#!/bin/bash

# Helper for pulling DOMAIN_NAME live to localhost
#
# @author Michael Cannon <michael@peimic.com>
# @version $Id: l2l_peimic,v 1.3 2011/09/26 09:59:45 peimic.comprock Exp $

# configuration vars
DOMAIN_NAME="mediaburn.org"
DOMAIN_USER="fitvaihr"

# load live2local function helpers
source ~/.skel/scripts/live2local.sh

# RSYNC_MODS="--max-size=2m --include=store/ --exclude=**/store/** --include=MediaContent/ --exclude=**/MediaContent/** --include=pdf/ --exclude=**/pdf/**"

l2l_site_wordpress
l2l_do_sync ${@}