#!/bin/bash

# Helper for pulling live DOMAIN_NAME to local
#
# @author Michael Cannon <michael@peimic.com>
# @version $Id: l2l_biceps_in2code,v 1.1 2011/09/26 13:03:58 peimic.comprock Exp $

# configuration vars
DOMAIN_NAME="old.wohin-mittags.de"
REMOTE_SERVER="root@wohin-mittags.de"
REMOTE_DIR_WWW="/var/www/vhosts/wohin-mittags.de/subdomains/old/httpdocs"


function l2l_get_config_wohin {
	DB_HOST=`grep -P "\bdb_server\b" ${FILE_CONFIG}`
	DB_HOST=`echo ${DB_HOST} | sed -e 's#");.*##g' -e 's#^.*, "##g'`

	DB_NAME=`grep -P "\bdb_name\b" ${FILE_CONFIG}`
	DB_NAME=`echo ${DB_NAME} | sed -e 's#");.*##g' -e 's#^.*, "##g'`

	DB_USER=`grep -P "\bdb_user\b" ${FILE_CONFIG}`
	DB_USER=`echo ${DB_USER} | sed -e 's#");.*##g' -e 's#^.*, "##g'`

	DB_PW=`grep -P "\bdb_passwort\b" ${FILE_CONFIG}`
	DB_PW=`echo ${DB_PW} | sed -e 's#");.*##g' -e 's#^.*, "##g'`
	DB_PW=`echo ${DB_PW} | sed -e 's#(#\\\(#g' -e 's#)#\\\)#g'`

	return
}


function l2l_site_wohin() {
	IS_TYPE="wohin"
	FILE_CONFIG="diner2.inc.php"
}

# load live2local function helpers
source ~/.skel/scripts/live2local.sh

l2l_site_wohin
l2l_do_sync ${@}