#!/bin/bash

# Helper for pulling multiple GA Institute properties to new server
#
# @author Michael Cannon <mc@aihr.us>

# base configuration vars
FILE_CONFIG_NO_OVERWRITE=1
HOSTS_NO_CREATE="true"
PERMS_MODE="dev"
REMOTE_SERVER="root@63.131.141.29"
VHOST_NO_CREATE="true"
WWW_GROUP="nobody"

source ~/.skel/scripts/live2local.sh

if [[ 0 = 1 ]]
then

l2l_reset
DOMAIN_NAME="accountability-matters.com"
WWW_USER="accountm"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_wordpress
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="aurora-farm.com"
WWW_USER="aurorafa"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_typo3
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="boernercommunications.com"
WWW_USER="boernerc"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_typo3
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="chattychild.com"
WWW_USER="chattych"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_typo3
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="communityinvestmentnetwork.org"
WWW_USER="communit"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_typo3
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="ga-institute.com"
WWW_USER="gainstit"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_typo3
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="brcmedicalgroup.com"
WWW_USER="brcmedic"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_typo3
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="gracechurchmassapequa.org"
WWW_USER="gracechu"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_typo3
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="hankboerner.com"
WWW_USER="hankboer"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_static
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="idealdenturelab.com"
WWW_USER="idealden"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_static
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="rba-consultants.com"
WWW_USER="rbaconsu"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_typo3
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="rowanblewitt.com"
WWW_USER="rowanble"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs/htdocs/"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_static
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="theblewittfoundation.com"
WWW_USER="theblewi"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_typo3
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="ga-lists.com"
WWW_USER="galists"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_phplist
l2l_do_sync ${@}


l2l_reset
DOMAIN_NAME="interpublicpreparedness.com"
WWW_USER="interpub"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_typo3
l2l_do_sync ${@}

l2l_reset_db
source ~/.skel/scripts/live2local.sh
l2l_site_phplist
l2l_do_sync db
fi


l2l_reset
DOMAIN_NAME="accountability-central.com"
WWW_USER="accounta"
REMOTE_DIR_WWW="/var/www/sites/${DOMAIN_NAME}/docs"
LOCAL_DIR_WWW="/home/${WWW_USER}/public_html"
source ~/.skel/scripts/live2local.sh
l2l_site_typo3
l2l_do_sync ${@}

l2l_reset_db
FILE_CONFIG="ox/var/www.${DOMAIN_NAME}.conf.php"
source ~/.skel/scripts/live2local.sh
l2l_site_openx
l2l_do_sync db