#!/bin/bash

# Helper for pulling DOMAIN_NAME live to localhost
#
# @author Michael Cannon <michael@peimic.com>
# @version $Id: l2l_chinaconnectnow,v 1.2 2011/09/25 11:19:23 peimic.comprock Exp $

# configuration vars
REMOTE_SERVER="server53.wowrack.com"
DOMAIN_USER="lpdengin"
DOMAIN_NAME="lpdengineering.com"
USE_FTP=1

# load live2local function helpers
source ~/.skel/scripts/live2local.sh

# LOCAL_DB_MODS[1]="UPDATE wp_2_options SET option_value = 'http://discoveren.localhost/' WHERE option_value LIKE 'http://discoveren.com/';"

l2l_site_wordpress
l2l_do_sync ${@}