#!/bin/bash

# Helper for pulling DOMAIN_NAME live to localhost
#
# @author Michael Cannon <michael@peimic.com>
# @version $Id: l2l_peimic,v 1.3 2011/09/26 09:59:45 peimic.comprock Exp $

# configuration vars
DOMAIN_NAME="lehre-tum.42.in2code.de"
REMOTE_DIR_WWW="/var/www/lehre-tum"
REMOTE_SERVER="root@141.0.20.71"
FILE_CONFIG_OVERWRITE_DENY=1

# load live2local function helpers
source ~/.skel/scripts/live2local.sh

l2l_site_wordpress
l2l_do_sync ${@}