#!/bin/bash

# Helper for pulling Stonebriar live to local
#
# @author Michael Cannon <michael@peimic.com>
# @version $Id: l2l_stonebriar,v 1.2 2011/09/23 05:13:46 peimic.comprock Exp $

# configuration vars
DOMAIN_NAME="af.stonebriar.org"
REMOTE_SERVER="michael@stonebriar01.managed.contegix.com"
REMOTE_DIR_WWW="/var/www/domains/stonebriar.org/af/htdocs"
RSYNC_MODS="--max-size=4M --include=wp-content/blogs.dir/ --exclude=**/wp-content/blogs.dir/**"

# load live2local function helpers
source ~/.skel/scripts/live2local.sh

# LOCAL_MODS[1]="cp ~/code/svn.in2code/in2code/in2master/trunk/_.htaccess .htaccess"
# LOCAL_MODS[2]="if [[ -e index.html ]]; then mv index.html index.maint.html; fi"

l2l_site_wordpress_multisite
l2l_do_sync ${@}