#!/bin/bash

# Prepare Remove Extra Media for release
#
# @author Michael Cannon <mc@aihr.us>

KEY="rmem"
DIR_UPLOAD="2013/09"
ID_PRODUCT=18566
ID_POST=0

source ~/.skel/bin/wpinit ${KEY}
echo

if [[ -z ${1} ]]
then
	echo "What's the version number?"
	echo
	exit 1
else
	VERSION=${1}
fi

wprelease ${KEY} ${VERSION} || exit 1;

if [[ -n ${2} ]]
then
	wpsvn ${KEY} ${VERSION} || exit 1;
else
	echo "wpsvn ${KEY} ${VERSION}"
fi

wpdocument ${KEY} ${DIR_UPLOAD} ${ID_PRODUCT} ${ID_POST}