#!/bin/sh

# Update TYPO3 for Stonebriar
#
# @author Michael Cannon <michael@peimic.com>

TYPO3_VERSION="4.5.19"
WWW_GROUP="apache"
WWW_USER="michael"
WWW_DIRS="/var/www/domains/stonebriar.org/newsletters/htdocs
/var/www/domains/stonebriar.org/www/htdocs
/var/www/domains/experiencestonebriar.org/www/htdocs"

for WWW_DIR in ${WWW_DIRS}
do
	echo cd ${WWW_DIR}

	# dev permisssions
	chattr -i ${WWW_DIR}
	~/bin/websitepermissions ${WWW_USER} ${WWW_GROUP} dev
	chown ${WWW_USER}:${WWW_GROUP} ${WWW_DIR}
	chmod 0770 ${WWW_DIR}

	# update TYPO3
	~/bin/t3upgrade.sh ${TYPO3_VERSION}
	rm -f typo3conf/temp_CACHED_*

	# production perms
	~/bin/websitepermissions ${WWW_USER} ${WWW_GROUP}
	chmod 0750 ${WWW_DIR}
	chattr +i ${WWW_DIR}
done