#!/bin/sh

# WordPress perms updater for Stonebriar
#
# @author Michael Cannon <michael@peimic.com>

WWW_GROUP="apache"
WWW_USER="michael"
WWW_DIRS="/var/www/domains/stonebriar.org/af/htdocs
/var/www/domains/stonebriar.org/blog/htdocs
/var/www/domains/stonebriar.org/ironman/htdocs
/var/www/domains/stonebriar.org/jrhigh/htdocs"

for WWW_DIR in ${WWW_DIRS}
do
	cd ${WWW_DIR}

	if [[ -z ${1} ]]
	then
		# dev permisssions
		chattr -i ${WWW_DIR}
		~/bin/websitepermissions ${WWW_GROUP} ${WWW_GROUP} dev
		chown ${WWW_GROUP}:${WWW_GROUP} ${WWW_DIR}
		chmod 0770 ${WWW_DIR}
	else
		# production perms
		~/bin/websitepermissions ${WWW_USER} ${WWW_GROUP}
		chmod 0750 ${WWW_DIR}
		chattr +i ${WWW_DIR}
	fi
done