#!/bin/bash

# Prepare Testimonials Widget Premium for release
#
# @author Michael Cannon <mc@aihr.us>

KEY="twp"
DIR_UPLOAD="2012/11"
ID_PRODUCT=14714
ID_POST=14635
ID_CHANGELOG=16129
ID_API=17826
ID_TODO=0

source ~/.skel/bin/wpinit ${KEY}
echo

if [[ -z ${1} ]]
then
	echo "What's the version number?"
	echo
	exit 1
fi

VERSION=${1}
wprelease ${KEY} ${VERSION} || exit 1;
wpdocument ${KEY} ${DIR_UPLOAD} ${ID_PRODUCT} ${ID_POST} ${ID_CHANGELOG} ${ID_API} ${ID_TODO}

open ${DOC_DOMAIN}/wp-admin/post.php?post=435668\&action=edit

open ${DOC_DOMAIN}/wp-admin/post.php?post=435676\&action=edit

open https://github.com/michael-cannon/testimonials-widget-premium/blob/master/UPGRADING.md
open ${DOC_DOMAIN}/wp-admin/post.php?post=1301973\&action=edit

open https://github.com/michael-cannon/testimonials-widget-premium/blob/master/DEPRECATED.md
open ${DOC_DOMAIN}/wp-admin/post.php?post=435693\&action=edit