#!/bin/bash

# Prepare Testimonials Widget Premium for release
#
# @author Michael Cannon <mc@aihr.us>

KEY="twp"

source ~/.skel/bin/custom/wpinit ${KEY}
echo

if [[ -z ${1} ]]
then
	echo "What's the version number?"
	echo
	exit 1
fi

VERSION=${1}
wprelease ${KEY} ${VERSION} || exit 1;

${CMD_SCP} ~/Downloads/zzz-wp/testimonials-widget-premium.zip aihrus@aihr.us:~/subdomains/updates/update/. || exit 1;
${CMD_SCP} ~/Downloads/zzz-wp/testimonials-widget-premium.zip aihrus@aihr.us:~/public_html/wp-content/uploads/edd/2012/11/. || exit 1;

# TODO auto feed our txt files to WP validator
##	URL_VALIDATE="http://wordpress.org/extend/plugins/about/validator/"
##	TXTS=`ls *.txt`
##
##	for TXT in ${TXTS}
##	do
##		echo Prepare ${TXT} for validation
##		# read TXT contents
##		# convert TXT to _POST
##		# submit URL
##		# open ${URL_VALIDATE} ${TXT}
##	done
##
##	echo

open http://wordpress.org/extend/plugins/about/validator/

# changelog
open http://aihr.us/wp-admin/post.php?post=16129\&action=edit

mvim ${SITE_WP_PLUGINS}/testimonials-widget-premium/readme.txt
# details
open http://aihr.us/wp-admin/post.php?post=14635\&action=edit
# product
open http://aihr.us/wp-admin/post.php?post=14714\&action=edit

mvim ~/Sites/zzz/testimonials-widget-premium/packages.php
echo ${CMD_SCP} ~/Sites/zzz/testimonials-widget-premium/packages.php aihrus@aihr.us:~/subdomains/updates/packages.php
echo