#!/bin/bash

# Prepare Testimonials Widget and Testimonials Widget Premium WordPress
# plugins for release
#
# @author Michael Cannon <mc@aihr.us>

PLUGINS="
testimonials-widget
testimonials-widget-premium
"

wpprep tw
