#!/bin/bash

# Prepare Testimonials Widget and Testimonials Widget Premium for release
#
# @author Michael Cannon <mc@aihr.us>

# TODO generalize

# TODO read readme head to parse out version
if [[ -z ${1} ]]
then
	echo "What's the version number?"
	exit
fi

KEY="tw"
VERSION=${1}

source ~/.skel/bin/custom/wpinit ${KEY}
echo

wppackage ${KEY}
wppush ${KEY}

# push svn and do WordPress release
cd ~/code/svn.wordpress
cd testimonials-widget
svn cleanup .
svn up --force
svn cp trunk tags/${VERSION}
svn ci -m "Release version ${VERSION}"

${CMD_SCP} ~/Downloads/testimonials-widget-premium.zip aihrus@aihr.us:~/subdomains/updates/update/.
${CMD_SCP} ~/Downloads/testimonials-widget-premium.zip aihrus@aihr.us:~/public_html/wp-content/uploads/edd/2012/11/.

# TODO auto feed our txt files to WP validator
##	URL_VALIDATE="http://wordpress.org/extend/plugins/about/validator/"
##	TXTS=`ls *.txt`
##
##	for TXT in ${TXTS}
##	do
##		echo Prepare ${TXT} for validation
##		# read TXT contents
##		# convert TXT to _POST
##		# submit URL
##		# open ${URL_VALIDATE} ${TXT}
##	done
##
##	echo

open http://wordpress.org/extend/plugins/about/validator/

mvim ~/Sites/wp/wp-content/plugins/testimonials-widget/changelog.txt
open http://aihr.us/wp-admin/post.php?post=16105\&action=edit

mvim ~/Sites/wp/wp-content/plugins/testimonials-widget-premium/changelog.txt
open http://aihr.us/wp-admin/post.php?post=16129\&action=edit

mvim ~/Sites/wp/wp-content/plugins/testimonials-widget-premium/readme.txt
open http://aihr.us/wp-admin/post.php?post=14635\&action=edit
open http://aihr.us/wp-admin/post.php?post=14714\&action=edit

mvim ~/Sites/zzz/testimonials-widget-premium/packages.php
echo ${CMD_SCP} ~/Sites/zzz/testimonials-widget-premium/packages.php aihrus@aihr.us:~/subdomains/updates/packages.php
echo

open http://aihr.us/wp-admin/update-core.php

for SCRIPT in ${SCRIPTS}
do
	echo
	${SCRIPT}
	echo
done