#!/bin/bash

# Prepare Testimonials Widget and Testimonials Widget Premium for release
#
# @author Michael Cannon <mc@aihr.us>

# TODO generalize

KEY="tw"

source ~/.skel/bin/custom/wpinit ${KEY}
echo

wplocalize ${KEY} commit
wpcompile ${KEY}
wpzip ${KEY}
wppush ${KEY}

# push svn and do WordPress release
cd ~/code/svn.wordpress
svn cleanup .
svn up --force

# TODO read readme head to parse out version
# TODO rcp trunk to tags

${CMD_SCP} ~/Downloads/testimonials-widget-premium.zip aihrus@aihr.us:~/subdomains/updates/update/.
${CMD_SCP} ~/Downloads/testimonials-widget-premium.zip aihrus@aihr.us:~/public_html/wp-content/uploads/edd/2012/11/.

##	URL_VALIDATE="http://wordpress.org/extend/plugins/about/validator/"
##	TXTS=`ls *.txt`
##
##	for TXT in ${TXTS}
##	do
##		echo Prepare ${TXT} for validation
##		# read TXT contents
##		# convert TXT to _POST
##		# submit URL
##		# open ${URL_VALIDATE} ${TXT}
##	done
##
##	echo

open http://wordpress.org/extend/plugins/about/validator/

mvim ~/Sites/wp/wp-content/plugins/testimonials-widget/changelog.txt
open http://aihr.us/wp-admin/post.php?post=16105\&action=edit

mvim ~/Sites/wp/wp-content/plugins/testimonials-widget-premium/changelog.txt
open http://aihr.us/wp-admin/post.php?post=16129\&action=edit

mvim ~/Sites/wp/wp-content/plugins/testimonials-widget-premium/readme.txt
open http://aihr.us/wp-admin/post.php?post=14635\&action=edit
open http://aihr.us/wp-admin/post.php?post=14714\&action=edit

mvim ~/Sites/wp/wp-content/plugins/testimonials-widget-premium/zzz/packages.php

echo ${CMD_SCP} ~/Sites/wp/wp-content/plugins/testimonials-widget-premium/zzz/packages.php aihrus@aihr.us:~/subdomains/updates/packages.php
echo

open http://aihr.us/wp-admin/update-core.php

for SCRIPT in ${SCRIPTS}
do
	echo
	${SCRIPT}
	echo
done