#!/bin/bash

# Tests for Testimonials Widget and Testimonials Widget Premium WordPress
# plugins
#
# When adding tests, make sure to escape &
#
# @author Michael Cannon <mc@aihr.us>


wpcompile twa

# TODO coding standard checks

if [[ -n ${1} ]]
then
	exit
fi


echo Any blatant errors?
open http://wp.localhost/wp-admin/

echo Do they show up in plugins?
open http://wp.localhost/wp-admin/plugins.php

echo Does plugin seach work?
open http://wp.localhost/wp-admin/network/plugin-install.php?tab=search\&s=schema-creator\&plugin-search-input=Search+Plugins

echo Does premium setting show up?
open http://wp.localhost/wp-admin/edit.php?post_type=testimonials-widget\&page=testimonialswidget_settings

echo Do widget options work?
open http://wp.localhost/wp-admin/widgets.php

echo Do shortcodes work?
open http://wp.localhost/tw-testing/

echo Does form work?
open http://wp.localhost/twp-form/?testmode=1

echo Does add view work?
open http://wp.localhost/wp-admin/post-new.php?post_type=testimonials-widget

echo Does single view work?
open http://wp.localhost/testimonial/robert-harm/

echo Do theme functions work?
open http://wp.localhost/theme-functions/

echo
wppush tw
echo

echo How does live look?
open http://aihr.us/good-work-deserves-good-words-testimonials-widget-examples/
