#!/bin/bash

cd ~/Downloads

if [[ -d testimonials-widget-premium ]]
then
	rm -rf testimonials-widget-premium
fi

if [[ -d testimonialswidgetpremium ]]
then
	rm -rf testimonialswidgetpremium
fi

git clone ssh://git_peimic@peimic.git.cloudforge.com/testimonialswidgetpremium.git

mv testimonialswidgetpremium testimonials-widget-premium
cd testimonials-widget-premium
rm -rf .git

cd ~/Downloads

rm -f testimonials-widget-premium.zip
zip -r testimonials-widget-premium.zip testimonials-widget-premium

rm -rf testimonials-widget-premium