#!/bin/bash

# Initial variables for WordPress plugins testing & release functions
#
# @author Michael Cannon <mc@aihr.us>

DIR_DOWNLOADS="${HOME}/Downloads"
DIR_SITES="${HOME}/Sites"
SITE_WP="${DIR_SITES}/wp"
SITE_WP_PLUGINS="${SITE_WP}/wp-content/plugins"

case "${1}" in
	"tw" )
		PLUGINS="
		testimonials-widget
		testimonials-widget-premium
		"
		;;
esac

if [[ -z ${PLUGINS} ]]
then
	PLUGINS="
	flickr-shortcode-importer
	testimonials-widget
	testimonials-widget-premium
	typo3-importer
	"
fi

if [[ -z ${SCRIPTS} ]]
then
	SCRIPTS=
fi
