#!/bin/bash

# Initial variables for WordPress plugins testing & release functions
#
# @author Michael Cannon <mc@aihr.us>

CMD_RSYNC="rsync -Pahz -e ssh --stats --delete-excluded --exclude=**/.git/** --exclude=**/.svn/** --exclude=**/zzz/**"
CMD_SCP="scp -r -p -C"
CMD_SSH="ssh -t"

DIR_DOWNLOADS="${HOME}/Downloads"
DIR_PLUGINS="wp-content/plugins"
DIR_SITES="${HOME}/Sites"

SITE_WP="${DIR_SITES}/wp"
SITE_WP_PLUGINS="${SITE_WP}/${DIR_PLUGINS}"
DIR_RULESETS="${SITE_WP_PLUGINS}/testimonials-widget/"

SSH_AIHRUS="aihrus@aihr.us"
PATH_AIHRUS="~/public_html"
CMD_SSH="${CMD_SSH} ${SSH_AIHRUS}"

case "${1}" in
	"twa" )
		PLUGINS="
		testimonials-widget
		testimonials-widget-premium
		"
		;;

	"tw" )
		PLUGINS="
		testimonials-widget
		"
		;;

	"twp" )
		PLUGINS="
		testimonials-widget-premium
		"
		;;
esac

if [[ -z ${PLUGINS} ]]
then
	PLUGINS="
	flickr-shortcode-importer
	testimonials-widget
	testimonials-widget-premium
	typo3-importer
	"
fi

if [[ -z ${SCRIPTS} ]]
then
	SCRIPTS=
fi
