#!/bin/bash

# Package WordPress plugins for testing or release
#
# @author Michael Cannon <mc@aihr.us>


if [[ -z ${1} ]]
then
	echo "Which plugin series key?"
	echo "Ex: tw"
	exit
fi

KEY=${1}

source ~/.skel/bin/custom/wpinit ${KEY}
echo

wplocalize ${KEY} commit
wpzip ${KEY}