#!/bin/bash

# Package WordPress plugins for testing or release
#
# @author Michael Cannon <mc@aihr.us>

if [[ -z ${1} || -z ${2} ]]
then
	echo ${0} plugin-key version-number
	echo
	exit 1
fi

KEY=${1}
