#!/bin/bash

# Package WordPress plugins for testing or release
#
# @author Michael Cannon <mc@aihr.us>


if [[ -z ${1} ]]
then
	echo "Which plugin series key?"
	echo "Ex: tw"
	echo
	exit 1
fi

KEY=${1}

wpversioncheck ${@} || exit 1;
wplocalize ${KEY} commit
wpzip ${KEY}