#!/bin/bash

# Localization and other preparation for WordPress plugins release
#
# @author Michael Cannon <mc@aihr.us>

DIR_SITES="${HOME}/Sites"
SITE_WP="${DIR_SITES}/wp"
SITE_WP_PLUGINS="${SITE_WP}/wp-content/plugins"
URL_VALIDATE="http://wordpress.org/extend/plugins/about/validator/"

case "${1}" in
	"tw" )
		PLUGINS="
		testimonials-widget
		testimonials-widget-premium
		"
		SCRIPTS="
		twtest
		"
		;;
esac

if [[ -z ${PLUGINS} ]]
then
	PLUGINS="
	flickr-shortcode-importer
	testimonials-widget
	testimonials-widget-premium
	typo3-importer
	"
	SCRIPTS=""
fi

echo

for PLUGIN in ${PLUGINS}
do
	DIR_PLUGIN="${SITE_WP_PLUGINS}/${PLUGIN}"

	if [[ ! -e ${DIR_PLUGIN} ]]
	then
		continue
	fi

	cd ${DIR_PLUGIN}

	echo Prepare plugin ${PLUGIN} at ${DIR_PLUGIN}

	FILES=`find . -type f \( -name "*.php" -o -name "*.inc" \)`

	for FILE in ${FILES}
	do
		# PHP compile test
		php -l ${FILE}

		echo Update text domain in ${FILE}
		php ${SITE_WP_PLUGINS}/i18n.svn.wordpress.org/add-textdomain.php -i ${PLUGIN} ${FILE}
		# clean up text domain spacing
		# `' , 'testimonials-widget-premium')` to `', 'testimonials-widget-premium' )`
		perl -pi -e "s#('|\") , '${PLUGIN}'\s?\)#\1, '${PLUGIN}' )#g" ${FILE}
	done

	echo Update localization to languages/${PLUGIN}.pot
	php ${SITE_WP_PLUGINS}/i18n.svn.wordpress.org/makepot.php wp-plugin ${DIR_PLUGIN} languages/${PLUGIN}.pot
	echo

##	TXTS=`ls *.txt`
##
##	for TXT in ${TXTS}
##	do
##		echo Prepare ${TXT} for validation
##		# read TXT contents
##		# convert TXT to _POST
##		# submit URL
##		# open ${URL_VALIDATE} ${TXT}
##	done
##
##	echo
done

for SCRIPT in ${SCRIPTS}
do
	echo
	${SCRIPT}
	echo
done
