#!/bin/bash

# Prepare WordPress plugins for release
#
# @author Michael Cannon <mc@aihr.us>


KEY=${1}

source ~/.skel/bin/custom/wpinit ${KEY}
echo

wplocalize ${KEY}
wpcompile ${KEY}

# remove phptidy 
find . \( -name "*.phptidybak~" -o -name ".phptidy-cache" \) -exec rm {} \;