#!/bin/bash

# Push WordPress plugins to Aihrus
#
# @author Michael Cannon <mc@aihr.us>

source ~/.skel/bin/custom/wpinit ${@}
echo

for PLUGIN in ${PLUGINS}
do
	DIR_PLUGIN="${SITE_WP_PLUGINS}/${PLUGIN}"
	if [[ ! -e ${DIR_PLUGIN} ]]
	then
		continue
	fi

	${CMD_RSYNC} ${DIR_PLUGIN} ${SSH_AIHRUS}:${PATH_AIHRUS}/${DIR_PLUGINS}/.

	echo
done
