#!/bin/bash

# Create branch release, package, and push WordPress plugin
#
# @author Michael Cannon <mc@aihr.us>

if [[ -z ${1} || -z ${2} ]]
then
	echo ${0} plugin-key version-number
	echo
	exit 1
else
	KEY=${1}
	VERSION=${2}
fi

source ~/.skel/bin/custom/wpinit ${KEY}
echo

wpversioncheck ${KEY} ${VERSION} || exit 1;
wplocalize ${KEY} commit || exit 1;

cd ${SITE_WP_PLUGINS}/${PLUGIN} || exit 1
git branch -f ${VERSION} || exit 1
git checkout ${VERSION} || exit 1
git push origin ${VERSION} || exit 1
git checkout master || exit 1
cd -

wpzip ${@} || exit 1;

open https://github.com/michael-cannon/${PLUGIN}/blob/master/CHANGELOG.md
open http://wordpress.org/extend/plugins/${PLUGIN}/
open http://testwp.localhost/wp-admin/update-core.php
open http://aihr.us/wp-admin/update-core.php
