#!/bin/bash

# Create branch release, package, and push WordPress plugin
#
# @author Michael Cannon <mc@aihr.us>

if [[ -z ${1} || -z ${2} ]]
then
	echo ${0} plugin-key version-number
	echo
	exit 1
fi

KEY=${1}
VERSION=${2}

source ~/.skel/bin/custom/wpinit ${KEY}
echo

cd ${SITE_WP_PLUGINS}/${PLUGIN} || exit 1
git branch ${VERSION} || exit 1
git checkout ${VERSION} || exit 1
git push origin ${VERSION} || exit 1
git checkout master || exit 1
cd -

wppackage ${@} || exit 1;
wppush ${@} || exit 1;
