#!/bin/bash

# Prepare Custom Bulk/Quick Edit for release
#
# @author Michael Cannon <mc@aihr.us>

KEY="cbqe"

source ~/.skel/bin/custom/wpinit ${KEY}
echo

if [[ -z ${1} ]]
then
	echo "What's the version number?"
	echo
	exit 1
fi

VERSION=${1}
wprelease ${KEY} ${VERSION} || exit 1;

# push svn and do WordPress release
cd ~/code/svn.wordpress
cd ${PLUGIN}
svn cleanup . || { echo "Unable to 'svn cleanup'"; exit 1; }
svn up --force || { echo "Unable to 'svn up --force'"; exit 1; }
git clone git@github.com:michael-cannon/${PLUGIN}.git || { echo "Unable to 'git
clone'"; exit 1; }
cd ${PLUGIN}
rm -rf .git
cp -r * ../trunk/.
cd ../trunk
svn add *
cd ..
rm -rf ${PLUGIN}

if [[ ! -d "tags/${VERSION}" ]]
then
	svn cp trunk tags/${VERSION}
	svn ci -m "Release version ${VERSION}" || { echo "Unable to 'svn ci'"; exit 1; }
	svn status
else
	echo
	echo Manually merge SVN files
	echo "svn cp trunk tags/${VERSION}"
	echo "svn ci -m \"Release version ${VERSION}\""
	echo
fi

open http://wordpress.org/extend/plugins/about/validator/

mvim ${SITE_WP_PLUGINS}/${PLUGIN}/changelog.txt
open http://aihr.us/wp-admin/post.php?post=16105\&action=edit

open http://testwp.localhost/wp-admin/update-core.php
open http://aihr.us/wp-admin/update-core.php
open http://wordpress.org/extend/plugins/${PLUGIN}/