#!/bin/bash

# Pull and compress WordPress plugins for release or beta testing
#
# @author Michael Cannon <mc@aihr.us>

source ~/.skel/bin/custom/wpinit ${@}
echo

for PLUGIN in ${PLUGINS}
do
	cd ${DIR_DOWNLOADS}

	if [[ -d ${PLUGIN} ]]
	then
		rm -rf ${PLUGIN}
	fi

	if [[ "testimonials-widget-premium" == ${PLUGIN} ]]
	then
		echo Prepare Testimonials Widget Premium
		git clone ssh://git_peimic@peimic.git.cloudforge.com/testimonialswidgetpremium.git ${PLUGIN}
	else
		echo Prepare ${PLUGIN} 
		svn co http://plugins.svn.wordpress.org/${PLUGIN}/trunk ${PLUGIN}
	fi

	cd ${PLUGIN}
	find . -type d \( -name ".git" -o -name ".svn" \) -exec rm -rf {} \;

	cd ${DIR_DOWNLOADS}

	FILE_ZIP="${PLUGIN}.zip"
	if [[ -e ${FILE_ZIP} ]]
	then
		rm -f ${FILE_ZIP}
	fi

	zip -r ${FILE_ZIP} ${PLUGIN}
	rm -rf ${PLUGIN}

	echo
done